// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaSuficiencia.Context;

#nullable disable

namespace ProvaSuficiencia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250805173157_AdicionandoModelos")]
    partial class AdicionandoModelos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ProvaSuficiencia.Domain.Comanda.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("ProvaSuficiencia.Domain.Comanda.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ProvaSuficiencia.Domain.Comanda.Produto", b =>
                {
                    b.HasOne("ProvaSuficiencia.Domain.Comanda.Comanda", "Comanda")
                        .WithMany("Produtos")
                        .HasForeignKey("ComandaId");

                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("ProvaSuficiencia.Domain.Comanda.Comanda", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
